explorer/urls.py
import threading

from django.conf import settings
from django.urls import include, path

from explorer.tasks import build_schema_cache_async
from explorer.views import (
    CreateQueryView,
    DeleteQueryView,
    DownloadFromSqlView,
    DownloadQueryView,
    ListQueryLogView,
    ListQueryView,
    PlayQueryView,
    QueryView,
)

urlpatterns = [
    path('', PlayQueryView.as_view(), name='explorer_index'),
    path('auth/', include('authbroker_client.urls', namespace='authbroker')),
    path('download/', DownloadFromSqlView.as_view(), name='download_sql'),
    path('queries/', ListQueryView.as_view(), name='list_queries'),
    path('queries/create/', CreateQueryView.as_view(), name='query_create'),
    path('queries/<int:query_id>/', QueryView.as_view(), name='query_detail'),
    path('queries/<int:query_id>/download/', DownloadQueryView.as_view(), name='download_query'),
    path('queries/<int:pk>/delete/', DeleteQueryView.as_view(), name='query_delete'),
    path('logs/', ListQueryLogView.as_view(), name='explorer_logs'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)),] + urlpatterns

# Build schema cache at startup in background
if not settings.MULTIUSER_DEPLOYMENT and not settings.TEST:

    def build_schema():
        for alias in settings.EXPLORER_CONNECTIONS:
            build_schema_cache_async(alias)

    t = threading.Thread(target=build_schema, args=(), kwargs={})
    t.setDaemon(True)
    t.start()

uploader/urls.py
from django.urls import path

from .views import (
    PipelineCreateView,
    PipelineCreatedView,
    PipelineDataUploadView,
    PipelineDataUploadedView,
    PipelineSelectView,
)

app_name = 'uploader'

urlpatterns = [
    path('', PipelineSelectView.as_view(), name='pipeline-select'),
    path('create', PipelineCreateView.as_view(), name='pipeline-create'),
    path('created/<str:slug>/', PipelineCreatedView.as_view(), name='pipeline-created'),
    path('upload/<str:slug>/', PipelineDataUploadView.as_view(), name='pipeline-data-upload'),
    path('uploaded/<str:slug>/', PipelineDataUploadedView.as_view(), name='pipeline-data-uploaded'),
]

uploader/models.py
from django.db import models
from django.utils.text import slugify
from storages.backends.s3boto3 import S3Boto3Storage


def csv_file_name(instance, filename):
    return f"{instance.pipeline.organisation}/{instance.pipeline.dataset}/{filename}"


class FileStorage(S3Boto3Storage):
    location = 'generic'


class Pipeline(models.Model):
    organisation = models.CharField(max_length=256, null=False, blank=False)
    dataset = models.CharField(max_length=256, null=False, blank=False)
    slug = models.SlugField(
        editable=False, max_length=256
    )

    @property
    def data_workspace_table_name(self):
        return f'{self.organisation}_{self.dataset}'

    def __str__(self):
        return f'{self.organisation} {self.dataset}'

    class Meta:
        unique_together = ('organisation', 'dataset')

    def save(
        self, *args, **kwargs
    ):
        if not self.pk:
            value = " ".join([self.organisation, self.dataset])
            self.slug = slugify(value)
        return super().save(*args, **kwargs)


class DataFile(models.Model):
    pipeline = models.ForeignKey('Pipeline', null=False, blank=False, on_delete=models.CASCADE)
    csv_file = models.FileField(storage=FileStorage(), upload_to=csv_file_name)

uploader/forms.py
from django import forms
from .models import Pipeline, DataFile


class PipelineForm(forms.ModelForm):

    class Meta:
        model = Pipeline
        fields = '__all__'
        widgets = {
            'organisation': forms.TextInput(attrs={'class': 'govuk-input'}),
            'dataset': forms.TextInput(attrs={'class': 'govuk-input'}),
        }


class DataFileForm(forms.ModelForm):

    class Meta:
        model = DataFile
        fields = ['csv_file']
        widgets = {
            'csv_file': forms.FileInput(attrs={'class': 'govuk-file-upload'}),
        }

    def __init__(self, *args, **kwargs):
        self.pipeline = kwargs.pop('pipeline')
        super().__init__(*args, **kwargs)

    def save(
        self, *args, **kwargs
    ):
        self.instance.pipeline = self.pipeline
        return super().save(*args, **kwargs)


class PipelineSelectForm(forms.Form):
    pipeline = forms.ModelChoiceField(
        queryset=Pipeline.objects.all(),
        empty_label=None,
    )

uploader/views.py
from .forms import PipelineForm, DataFileForm, PipelineSelectForm
from .models import Pipeline

from django.shortcuts import reverse, get_object_or_404
from django.views.generic import CreateView, DetailView, FormView
from django.http import HttpResponseRedirect


class PipelineSelectView(FormView):
    template_name = 'dsu/pipeline_select.html'
    form_class = PipelineSelectForm

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['heading'] = 'Select pipeline'
        return context_data

    def form_valid(self, form):
        url = reverse(
            'uploader:pipeline-data-upload', kwargs={'slug': form.cleaned_data['pipeline'].slug}
        )
        return HttpResponseRedirect(url)


class PipelineCreateView(CreateView):
    template_name = 'dsu/pipeline_create.html'
    form_class = PipelineForm

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['heading'] = 'Create dataset'
        return context_data

    def get_success_url(self):
        return reverse('uploader:pipeline-created', kwargs={'slug': self.object.slug})


class PipelineCreatedView(DetailView):
    template_name = 'dsu/pipeline_created.html'
    model = Pipeline
    slug_url_kwarg = 'slug'


class PipelineDataUploadView(CreateView):
    template_name = 'dsu/pipeline_data_upload.html'
    form_class = DataFileForm

    def get_pipeline(self):
        return get_object_or_404(Pipeline, slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        pipeline = self.get_pipeline()
        context_data['pipeline'] = pipeline
        context_data['heading'] = f'Upload data to {pipeline} pipeline'
        return context_data

    def get_success_url(self):
        return reverse(
            'uploader:pipeline-data-uploaded',
            kwargs={'slug': self.object.pipeline.slug}
        )

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['pipeline'] = self.get_pipeline()
        return kwargs


class PipelineDataUploadedView(DetailView):
    template_name = 'dsu/pipeline_data_uploaded.html'
    model = Pipeline
    slug_url_kwarg = 'slug'

uploader/templates/dsu/pipeline_create.html
{% extends 'core/base.html' %}
{% load i18n %}

{% block content %}
<form method="post" name="pipeline_form" enctype="multipart/form-data">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            {% csrf_token %}
            {% include 'form/error_summary.html' %}

            <fieldset class="govuk-fieldset">
                <legend class="govuk-fieldset__legend govuk-fieldset__legend--l">
                    <h1 class="govuk-fieldset__heading">{{ heading }}</h1>
                </legend>

                {% include 'form/input_field.html' with field=form.organisation %}
                {% include 'form/input_field.html' with field=form.dataset %}

                <div class="gov-form-group govuk-!-padding-top-6">
                    <ul class="govuk-list">
                        <li>
                            <input type="submit" value="{% trans 'Create' %}" class="govuk-button govuk-!-margin-bottom-4">
                        </li>
                    </ul>

                </div>
            </fieldset>
        </div>
    </div>
</form>
{% endblock content %}

uploader/templates/dsu/pipeline_created.html
{% extends 'core/base.html' %}
{% load i18n %}

{% block content %}
<div class="govuk-panel govuk-panel--confirmation">
    <h1 class="govuk-panel__title">Dataset pipeline created</h1>
    <div class="govuk-panel__body"><strong>{{ pipeline }}</strong></div>
</div>
<a href="{% url 'uploader:pipeline-data-upload' slug=pipeline.slug %}" role="button" draggable="false" class="govuk-button govuk-button--start" data-module="govuk-button">
  Continue to upload data
  <svg class="govuk-button__start-icon" xmlns="http://www.w3.org/2000/svg" width="17.5" height="19" viewBox="0 0 33 40" aria-hidden="true" focusable="false">
    <path fill="currentColor" d="M0 0h13l20 20-20 20H0l20-20z" />
  </svg>
</a>
{% endblock content %}

uploader/templates/dsu/pipeline_data_upload.html
{% extends 'core/base.html' %}
{% load i18n %}

{% block content %}

<form method="post" name="pipeline_form" enctype="multipart/form-data">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            {% csrf_token %}
            {% include 'form/error_summary.html' %}

            <fieldset class="govuk-fieldset">
                <legend class="govuk-fieldset__legend govuk-fieldset__legend--l">
                    <h1 class="govuk-fieldset__heading">{{ heading }}</h1>
                </legend>

                {% include 'form/input_field.html' with field=form.csv_file %}

                <div class="gov-form-group govuk-!-padding-top-6">
                    <ul class="govuk-list">
                        <li>
                            <input type="submit" value="{% trans 'Upload' %}" class="govuk-button govuk-!-margin-bottom-4">
                        </li>
                    </ul>
                </div>
            </fieldset>
        </div>
    </div>
</form>

{% endblock content %}

uploader/templates/dsu/pipeline_data_uploaded.html
{% extends 'core/base.html' %}
{% load i18n %}

{% block content %}
<div class="govuk-panel govuk-panel--confirmation">
    <h1 class="govuk-panel__title">Data successfully uploaded</h1>
    <div class="govuk-panel__body">to&nbsp;<strong>{{ pipeline }}</strong>&nbsp;pipeline</div>
</div>
<a href="{% url 'uploader:pipeline-select' %}" role="button" draggable="false" class="govuk-button govuk-button--start" data-module="govuk-button">
    Add more data
    <svg class="govuk-button__start-icon" xmlns="http://www.w3.org/2000/svg" width="17.5" height="19" viewBox="0 0 33 40" aria-hidden="true" focusable="false">
        <path fill="currentColor" d="M0 0h13l20 20-20 20H0l20-20z" />
    </svg>
</a>
{% endblock content %}

uploader/templates/dsu/pipeline_select.html
{% extends 'core/base.html' %}
{% load i18n %}

{% block content %}
<form method="post" name="pipeline_form" enctype="multipart/form-data">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            {% csrf_token %}
            {% include 'form/error_summary.html' %}

            {% if form.pipeline.field.choices %}
                <fieldset class="govuk-fieldset">
                    {% include 'form/input_radio_field.html' with field=form.pipeline label='Existing datasets' %}
                    <div class="gov-form-group govuk-!-padding-top-6">
                        <ul class="govuk-list">
                            <li>
                                <input type="submit" value="{% trans 'Update dataset' %}" class="govuk-button govuk-!-margin-bottom-4">
                            </li>
                        </ul>
                    </div>
                </fieldset>
            {% endif %}

            <a href="{% url 'uploader:pipeline-create' %}" role="button" draggable="false" class="govuk-button govuk-button--start" data-module="govuk-button">
                Add new dataset
                <svg class="govuk-button__start-icon" xmlns="http://www.w3.org/2000/svg" width="17.5" height="19" viewBox="0 0 33 40" aria-hidden="true" focusable="false">
                    <path fill="currentColor" d="M0 0h13l20 20-20 20H0l20-20z" />
                </svg>
            </a>
        </div>
    </div>
</form>
{% endblock content %}