explorer/urls.py
import threading

from django.conf import settings
from django.urls import include, path

from explorer.tasks import build_schema_cache_async
from explorer.views import (
    CreateQueryView,
    DeleteQueryView,
    DownloadFromSqlView,
    DownloadQueryView,
    ListQueryLogView,
    ListQueryView,
    PlayQueryView,
    QueryView,
)

urlpatterns = [
    path('', PlayQueryView.as_view(), name='explorer_index'),
    path('auth/', include('authbroker_client.urls', namespace='authbroker')),
    path('download/', DownloadFromSqlView.as_view(), name='download_sql'),
    path('queries/', ListQueryView.as_view(), name='list_queries'),
    path('queries/create/', CreateQueryView.as_view(), name='query_create'),
    path('queries/<int:query_id>/', QueryView.as_view(), name='query_detail'),
    path('queries/<int:query_id>/download/', DownloadQueryView.as_view(), name='download_query'),
    path('queries/<int:pk>/delete/', DeleteQueryView.as_view(), name='query_delete'),
    path('logs/', ListQueryLogView.as_view(), name='explorer_logs'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)),] + urlpatterns

# Build schema cache at startup in background
if not settings.MULTIUSER_DEPLOYMENT and not settings.TEST:

    def build_schema():
        for alias in settings.EXPLORER_CONNECTIONS:
            build_schema_cache_async(alias)

    t = threading.Thread(target=build_schema, args=(), kwargs={})
    t.setDaemon(True)
    t.start()

explorer/models.py
from __future__ import unicode_literals

import logging
import uuid
from time import time

import six
from django.conf import settings
from django.db import DatabaseError, models

try:
    from django.urls import reverse
except ImportError:
    from django.core.urlresolvers import reverse
from dynamic_models.models import AbstractFieldSchema, AbstractModelSchema  # noqa: I202

from explorer.utils import (
    extract_params,
    get_params_for_url,
    get_valid_connection,
    shared_dict_update,
    swap_params,
)

POSTGRES_VENDOR = 'postgresql'

logger = logging.getLogger(__name__)


@six.python_2_unicode_compatible
class Query(models.Model):
    title = models.CharField(max_length=255)
    sql = models.TextField()
    description = models.TextField(null=True, blank=True)
    created_by_user = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)
    last_run_date = models.DateTimeField(auto_now=True)
    connection = models.CharField(
        blank=True,
        null=True,
        max_length=128,
        help_text="Name of DB connection (as specified in settings) to use for this query."
        " Will use EXPLORER_DEFAULT_CONNECTION if left blank",
    )

    def __init__(self, *args, **kwargs):
        self.params = kwargs.get('params')
        kwargs.pop('params', None)
        super(Query, self).__init__(*args, **kwargs)

    class Meta:
        ordering = ['title']
        verbose_name_plural = 'Queries'

    def __str__(self):
        return six.text_type(self.title)

    def get_run_count(self):
        return self.querylog_set.count()

    def avg_duration(self):
        return self.querylog_set.aggregate(models.Avg('duration'))['duration__avg']

    def final_sql(self):
        return swap_params(self.sql, self.available_params())

    def execute_with_logging(self, executing_user, page, limit, timeout):
        ql = self.log(executing_user)
        ret = self.execute(page, limit, timeout)
        ql.duration = ret.duration
        ql.save()
        return ret, ql

    def execute(self, page, limit, timeout):
        result = QueryResult(
            self.final_sql(),
            get_valid_connection(self.connection),
            page,
            limit=limit,
            timeout=timeout,
        )
        result.process()
        return result

    def available_params(self):
        """
        Merge parameter values into a dictionary of available parameters

        :param param_values: A dictionary of Query param values.
        :return: A merged dictionary of parameter names and values.
         Values of non-existent parameters are removed.
        """

        p = extract_params(self.sql)
        if self.params:
            shared_dict_update(p, self.params)
        return p

    def get_absolute_url(self):
        return reverse("query_detail", kwargs={'query_id': self.id})

    @property
    def params_for_url(self):
        return get_params_for_url(self)

    def log(self, user=None):
        if user:
            # In Django<1.10, is_anonymous was a method.
            try:
                is_anonymous = user.is_anonymous()
            except TypeError:
                is_anonymous = user.is_anonymous
            if is_anonymous:
                user = None
        ql = QueryLog(
            sql=self.final_sql(), query_id=self.id, run_by_user=user, connection=self.connection
        )
        ql.save()
        return ql


class QueryLog(models.Model):

    sql = models.TextField(null=True, blank=True)
    query = models.ForeignKey(Query, null=True, blank=True, on_delete=models.SET_NULL)
    run_by_user = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE
    )
    run_at = models.DateTimeField(auto_now_add=True)
    duration = models.FloatField(blank=True, null=True)  # milliseconds
    connection = models.CharField(blank=True, null=True, max_length=128)

    @property
    def is_playground(self):
        return self.query_id is None

    class Meta:
        ordering = ['-run_at']


class QueryResult(object):
    def __init__(self, sql, connection, page, limit, timeout):
        self.sql = sql
        self.connection = connection
        self.limit = limit
        self.timeout = timeout
        self._row_count = None
        self._data = []
        self._headers = []
        self._summary = {}
        self._description = None
        self.duration = None
        self.page = page
        self.execute_query()

    def execute_query(self):
        with self.connection.cursor() as cursor:
            sql_query = SQLQuery(cursor, self.sql, self.limit, self.page, self.timeout)
            self._data = sql_query.get_results()
            self._description = sql_query.description
            self._headers = self._get_headers()
            self._row_count = sql_query.count
            self.duration = sql_query.duration

    @property
    def data(self):
        return self._data or []

    @property
    def row_count(self):
        if self._row_count is None:
            return len(self.data)
        return self._row_count

    @property
    def headers(self):
        return self._headers or []

    @property
    def header_strings(self):
        return [str(h) for h in self.headers]

    def _get_headers(self):
        return (
            [ColumnHeader(d[0]) for d in self._description]
            if self._description
            else [ColumnHeader('--')]
        )

    def _get_numerics(self):
        if self.data:
            d = self.data[0]
            return [
                ix
                for ix, _ in enumerate(self._description)
                if not isinstance(d[ix], six.string_types) and six.text_type(d[ix]).isnumeric()
            ]
        return []

    def column(self, ix):
        return [r[ix] for r in self.data]

    def process(self):
        start_time = time()
        self.process_columns()
        logger.info("Explorer Query Processing took %sms." % ((time() - start_time) * 1000))

    def process_columns(self):
        for ix in self._get_numerics():
            self.headers[ix].add_summary(self.column(ix))


class SQLQuery(object):
    def __init__(self, cursor, sql, limit, page, timeout):
        self.cursor = cursor
        self.sql = sql
        self.limit = limit
        self.page = page
        self.timeout = timeout
        self.duration = 0
        self._cursor_name = None
        self._count = 0
        self._description = None

    @property
    def count(self):
        if not self._count and self.cursor.db.vendor == POSTGRES_VENDOR:
            # trim whitespace and semicolons from the end of the query string
            sql = self.sql.rstrip().rstrip(';')
            self.cursor.execute(f'select count(*) from ({sql}) t')
            self._count = self.cursor.fetchone()[0]
        return self._count

    def execute(self):
        start_time = time()
        try:
            self._execute()
        except DatabaseError as e:
            raise e
        self.duration = (time() - start_time) * 1000

    def _execute(self):
        if self.cursor.db.vendor == POSTGRES_VENDOR:
            self.cursor.execute(f'SET statement_timeout = {self.timeout}')
            self.cursor.execute(f'DECLARE {self.cursor_name} CURSOR WITH HOLD FOR {self.sql}')
            if self.page and self.page > 1:
                offset = (self.page - 1) * self.limit
                self.cursor.execute(f'MOVE {offset} FROM {self.cursor_name}')
            self.cursor.execute(f'FETCH {self.limit} FROM {self.cursor_name}')
        else:
            self.cursor.execute(self.sql)

    def get_results(self):
        self.execute()
        self._description = self.cursor.description or []
        results = [list(r) for r in self.cursor]
        if self.cursor.db.vendor == POSTGRES_VENDOR:
            self.cursor.execute(f'CLOSE {self.cursor_name}')
        return results

    @property
    def cursor_name(self):
        if not self._cursor_name:
            self._cursor_name = 'cur_%s' % str(uuid.uuid4()).replace('-', '')[:10]
        return self._cursor_name

    @property
    def description(self):
        return self._description


@six.python_2_unicode_compatible
class ColumnHeader(object):
    def __init__(self, title):
        self.title = title.strip()
        self.summary = None

    def add_summary(self, column):
        self.summary = ColumnSummary(self, column)

    def __str__(self):
        return self.title


@six.python_2_unicode_compatible
class ColumnStat(object):
    def __init__(self, label, statfn, precision=2, handles_null=False):
        self.label = label
        self.statfn = statfn
        self.precision = precision
        self.handles_null = handles_null

    def __call__(self, coldata):
        self.value = round(float(self.statfn(coldata)), self.precision) if coldata else 0

    def __str__(self):
        return self.label


@six.python_2_unicode_compatible
class ColumnSummary(object):
    def __init__(self, header, col):
        self._header = header
        self._stats = [
            ColumnStat("Sum", sum),
            ColumnStat("Avg", lambda x: float(sum(x)) / float(len(x))),
            ColumnStat("Min", min),
            ColumnStat("Max", max),
            ColumnStat("NUL", lambda x: int(sum(map(lambda y: 1 if y is None else 0, x))), 0, True),
        ]
        without_nulls = list(map(lambda x: 0 if x is None else x, col))

        for stat in self._stats:
            stat(col) if stat.handles_null else stat(without_nulls)

    @property
    def stats(self):
        return {c.label: c.value for c in self._stats}

    def __str__(self):
        return str(self._header)


class ModelSchema(AbstractModelSchema):
    name = models.CharField(max_length=256, unique=True)


class FieldSchema(AbstractFieldSchema):
    name = models.CharField(max_length=256, unique=True)

explorer/forms.py
from django.forms import CharField, Field, ModelForm, ValidationError
from django.forms.widgets import Select

from explorer.app_settings import EXPLORER_CONNECTIONS, EXPLORER_DEFAULT_CONNECTION
from explorer.models import Query


class SqlField(Field):
    def validate(self, value):
        query = value.strip().upper()
        if not any([query.startswith("SELECT"), query.startswith("WITH")]):
            raise ValidationError(
                "Enter a SQL statement starting with SELECT or WITH", code="InvalidSql"
            )


class QueryForm(ModelForm):

    sql = SqlField()
    connection = CharField(widget=Select, required=False)
    title = CharField(
        error_messages={
            'required': 'Enter a title for the query',
            'max_length': 'The title for the query must be 255 characters or fewer',
        }
    )

    def __init__(self, *args, **kwargs):
        super(QueryForm, self).__init__(*args, **kwargs)
        self.fields['connection'].widget.choices = self.connections
        if not self.instance.connection:
            self.initial['connection'] = EXPLORER_DEFAULT_CONNECTION
        self.fields['connection'].widget.attrs['class'] = 'form-control'

    def clean(self):
        if self.instance and self.data.get('created_by_user', None):
            self.cleaned_data['created_by_user'] = self.instance.created_by_user
        return super(QueryForm, self).clean()

    @property
    def created_by_user_email(self):
        return self.instance.created_by_user.email if self.instance.created_by_user else '--'

    @property
    def created_at_time(self):
        return self.instance.created_at.strftime('%Y-%m-%d')

    @property
    def connections(self):
        return [(v, k) for k, v in EXPLORER_CONNECTIONS.items()]

    class Meta:
        model = Query
        fields = ['title', 'sql', 'description', 'connection']

explorer/templates/explorer/export_buttons.html
{% for key, name in exporters %}
    {% if query and query.id %}
        {% if query.params %}
          <li><a href="{% url "download_query" query.id %}?format={{ key }}&params={{ query.params_for_url }}">{{ name }}</a></li>
        {% else %}
          <li><a href="{% url "download_query" query.id %}?format={{ key }}">{{ name }}</a></li>
        {% endif %}
    {% else %}
        <li><input type="submit" value="{{ name }}" data-format="{{ key }}" class="download-button btn btn-link" /></li>
    {% endif %}
{% endfor %}

explorer/templates/explorer/home.html
{% extends 'explorer/base.html' %}

{% load explorer_tags %}

{% block title %}{% if form.errors %}Error: {% endif %}Data Explorer - Home{% endblock %}
{% block content %}
  <div class="govuk-width-container">
    <div class="govuk-grid-row">
      <div class="govuk-grid-column-full" id="query_area">
        {% if form.errors %}
          <div class="govuk-error-summary" aria-labelledby="error-summary-title" role="alert" tabindex="-1"
               data-module="govuk-error-summary">
            <h2 class="govuk-error-summary__title" id="error-summary-title">
              There is a problem
            </h2>
            <div class="govuk-error-summary__body">
              <ul class="govuk-list govuk-error-summary__list">
                {% for field, errors in form.errors.items %}
                  {% for error in errors %}
                    <li>
                      <a href="#id_{{ field }}">{{ error }}</a>
                    </li>
                  {% endfor %}
                {% endfor %}
              </ul>
            </div>
          </div>
        {% endif %}

        <h1 class="govuk-heading-xl govuk-!-margin-bottom-2">
          Welcome to Data Explorer
        </h1>

        <p class="govuk-body govuk-!-margin-top-6 govuk-!-margin-bottom-6">
          You can run a query on this page or see your <a href="{% url 'list_queries' %}" class="govuk-link">saved
          queries</a>.
        </p>

        <div class="govuk-tabs" data-module="govuk-tabs">
          <h2 class="govuk-tabs__title">
            Contents
          </h2>
          <ul class="govuk-tabs__list">
            <li class="govuk-tabs__list-item govuk-tabs__list-item--selected">
              <a class="govuk-tabs__tab" href="#query-tab">
                Query
              </a>
            </li>
            <li class="govuk-tabs__list-item">
              <a class="govuk-tabs__tab" href="#database-tab">
                Database
              </a>
            </li>
          </ul>
          <div class="govuk-tabs__panel" id="query-tab">
            <h2 class="govuk-heading-l">Query</h2>

            <form role="form" action="{{ form_action }}" method="post" id="editor">
              {% csrf_token %}

              <fieldset class="govuk-fieldset">
                {% if form.connections|length > 1 %}
                  <div class="govuk-form-group">
                    <label class="govuk-label" for="id_connection">
                      Connection
                    </label>
                    <select class="govuk-select" id="id_connection" name="connection">
                      {% for value, label in form.connections %}
                        <option value="{{ value|lower }}"{% if form.connection.value == value %} selected{% endif %}>
                          {{ label }}
                        </option>
                      {% endfor %}
                    </select>
                  </div>
                {% else %}
                  {# still need to submit the connection, just hide the UI element #}
                  <div style="display: none">
                    {{ form.connection }}
                  </div>
                {% endif %}

                {# We apply `id_sql` because that matches the id generated by the form for the `sql` field. We don't use #}
                {# that ID on the GOV.UK textarea itself because it's disabled and hidden, and therefore not a valid anchor #}
                {# target. Placing the id on the form group means that when the error is clicked we are still taken to the #}
                {# correct place on the page. #}
                <div id="id_sql" class="govuk-form-group {% if form.sql.errors %} govuk-form-group--error {% endif %}">
                  <p class="govuk-label">
                    Your SQL query
                  </p>
                  {% if form.sql.errors %}
                    {% for error in form.sql.errors %}
                      <span id="sql-error" class="govuk-error-message">
                              <span class="govuk-visually-hidden">Error:</span> {{ error|escape }}
                          </span>
                    {% endfor %}
                  {% endif %}
                  <div class="govuk-textarea" id="gov-uk-sql-wrapper" rows="10">
                    <div id="ace-sql-editor">{{ form.sql.value|default_if_none:"" }}</div>
                  </div>
                  <textarea aria-label="Sql" style="display: none;"
                            name="sql" id="original-sql">{{ form.sql.value|default_if_none:"" }}</textarea>

                  <div class="govuk-form-group">

                    <button class="govuk-button" data-module="govuk-button" name="action" value="run">
                      Run
                    </button>

                    <button class="govuk-button govuk-button--secondary govuk-!-margin-left-3"
                            data-module="govuk-button" name="action" value="save">
                      Save
                    </button>

                    <button class="govuk-button govuk-button--secondary govuk-!-margin-left-3"
                            data-module="govuk-button" type="button" id="format_button">
                      Format SQL
                    </button>

                  </div>

                  <input aria-label="Title" type="govuk-visually-hidden" value="{{ form.title.value|default_if_none:"Playground Query" }}" name="title" hidden/>
                </div>
              </fieldset>



              {% if headers %}
                <div class="govuk-grid-row">
                  <div class="govuk-grid-column-full">
                    <p class="govuk-heading-m govuk-!-margin-bottom-2">
                      Query result
                    </p>
                    <p class="govuk-body">
                      {% if rows > total_rows %}
                        Showing {{ total_rows }} rows from a total of {{ total_rows }}
                      {% else %}
                        Showing {{ rows }} rows from a total of {{ total_rows }}
                      {% endif %}
                    </p>
                    <p class="govuk-body">
			                Execution time: {{ duration|format_duration }}
                    </p>
                    <div class="scrollable-table">
                      <table class="govuk-table">
                        <thead class="govuk-table">
                        <tr class="govuk-table__row">
                          {% for header in headers %}
                            <th class="govuk-table__header">{{ header }}</th>
                          {% endfor %}
                        </tr>

                        <tbody class="govuk-table__body">
                        {% if data %}
                          {% for row in data %}
                            <tr class="govuk-table__row">
                              {% for column in row %}
                                <td class="govuk-table__cell">
                                  {{ column }}
                                </td>
                              {% endfor %}
                            </tr>
                          {% endfor %}
                        {% endif %}
                        </tbody>

                        </thead>
                      </table>
                    </div>

                    <div class="govuk-grid-row govuk-!-margin-top-4">
                      <div class="govuk-grid-column-full">
                          <span class="govuk-label app-label--inline" for="query-page">Show page </span>
                          <input class="govuk-input govuk-input--width-5 app-input--inline" id="query-page"
                                 name="query-page"
                                 value="{{ page }}"/>
                          <span class="govuk-body"> with </span>
                          <input class="govuk-input govuk-input--width-5 app-input--inline" id="query-rows"
                                 name="query-rows"
                                 value="{{ rows }}" type="number"/>
                          <span class="govuk-label app-label--inline" for="query-rows"> results per page</span>
                          <button class="govuk-button govuk-!-margin-left-5" data-module="govuk-button" name="action" value="fetch-page">
                            Fetch page
                          </button>
                      </div>
                    </div>

                    <button class="govuk-button govuk-button--secondary" data-module="govuk-button" name="action" value="download-csv">
                      Download CSV
                    </button>

                    <button class="govuk-button govuk-button--secondary govuk-!-margin-left-4" data-module="govuk-button" name="action" value="download-excel">
                      Download Excel
                    </button>

                    <button class="govuk-button govuk-button--secondary govuk-!-margin-left-4" data-module="govuk-button" name="action" value="download-json">
                      Download JSON
                    </button>
                  </div>
                </div>
              {% endif %}
            </form>
          </div>
          <div class="govuk-tabs__panel" id="database-tab">
            <h2 class="govuk-heading-l">Database</h2>
            <p class="govuk-body">
              You can see the database tables you have access to here.
            </p>

            {% include 'explorer/schema.html' %}
          </div>
        </div>

      </div>

    </div>

  </div>

  {% load render_bundle from webpack_loader %}
  {% render_bundle 'query' %}
  {% render_bundle 'schema' %}

{% endblock content %}

explorer/templates/explorer/params.html
{% if params %}
<div class="panel-footer">
  <div class="form-inline">
  {% for k, v in params.items %}
      <div class="form-group">
          <label for="{{ k }}_param" class="control-label col-sm-4">{{ k }}:</label>
          <div class="col-sm-7">
              <input type="text" data-param="{{ k }}" class="param form-control" name="{{ k }}_param" id="{{ k }}_param" placeholder="parameter" value="{{ v }}" />
          </div>
          <div class="col-sm-1"></div>
      </div>
  {% endfor %}
  </div>
</div>
{% endif %}

explorer/templates/explorer/query.html
{% extends 'explorer/base.html' %}

{% load explorer_tags %}

{% block title %}{% if form.errors %}Error: {% endif%}Data Explorer - New query{% endblock %}

{% block back_button %}
  {% if backlink %}
    <a href="{{ backlink }}" class="govuk-back-link">Back</a>
  {% endif %}
{% endblock %}

{% block content %}
<div class="govuk-width-container">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-full" id="query_area">
            {% if form.errors %}
                <div class="govuk-error-summary" aria-labelledby="error-summary-title" role="alert" tabindex="-1" data-module="govuk-error-summary">
                    <h2 class="govuk-error-summary__title" id="error-summary-title">
                        There is a problem
                    </h2>
                    <div class="govuk-error-summary__body">
                        <ul class="govuk-list govuk-error-summary__list">
                            {% for field, errors in form.errors.items %}
                                {% for error in errors %}
                                    <li>
                                        <a href="#id_{{ field }}">{{ error }}</a>
                                    </li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            {% endif %}
            <h1 class="govuk-heading-m govuk-!-margin-bottom-2">
                {% if query %}
                    {{ query.title }}
                    <a class="govuk-link" href="{% url 'explorer_logs' %}?query_id={{ query.id }}">History</a>
                {% else %}
                    New Query
                {% endif %}
            </h1>
            <fieldset class="govuk-fieldset">
                {% if message %}
                    <div class="govuk-warning-text">
                        <span class="govuk-warning-text__icon" aria-hidden="true">!</span>
                        <strong class="govuk-warning-text__text">
                            {{ message }}
                        </strong>
                    </div>
                {% endif %}

                {% if query %}
                    <form action="{% url 'query_detail' query.id %}" method="post" id="editor">{% csrf_token %}
                {% else %}
                    <form action="{% url 'query_create' %}" method="post" id="editor">{% csrf_token %}
                {% endif %}

                <div class="govuk-form-group{% if form.title.errors %} govuk-form-group--error {% endif %}">
                    <label class="govuk-label" for="id_title">
                        Title
                    </label>
                    {% if form.title.errors %}
                        {% for error in form.title.errors %}
                            <span id="title-error" class="govuk-error-message">
                                <span class="govuk-visually-hidden">Error:</span> {{ error|escape }}
                            </span>
                        {% endfor %}
                    {% endif %}
                    <input class="govuk-input govuk-input--width-30" id="id_title" name="title" type="text" value="{{ form.title.value|default_if_none:"" }}" />
                </div>

                <div class="govuk-form-group">
                    {% if form.connections|length > 1 %}
                        <label class="govuk-label" for="id_connection">
                            Connection
                        </label>
                        <select class="govuk-select" id="id_connection" name="connection">
                            {% for value, label in form.connections %}
                                <option value="{{ value }}"{% if form.connection.value == value %} selected{% endif %}>{{ label }}</option>
                            {% endfor %}
                        </select>
                    {% else %}
                        {# still need to submit the connection, just hide the UI element #}
                        <div style="display: none">
                          {{ form.connection }}
                        </div>
                    {% endif %}
                </div>

                <div class="govuk-form-group">
                    <label class="govuk-label" for="id_description">
                        Description
                    </label>
                    <textarea class="govuk-textarea" id="id_description" name="description" cols="40" rows="2">{{ form.description.value|default_if_none:"" }}</textarea>
                </div>
                <input type="hidden" id="id_created_by_user" name="created_by_user" value="{{ form.created_by_user_email }}" />

                {# We apply `id_sql` to the form group here to match the structure in `home.html` #}
                <div id="id_sql" class="govuk-form-group {% if form.sql.errors %} govuk-form-group--error {% endif %}">
                    <label class="govuk-label" for="original-sql">
                        SQL
                    </label>
                    {% if form.sql.errors %}
                        {% for error in form.sql.errors %}
                            <span id="sql-error" class="govuk-error-message">
                                <span class="govuk-visually-hidden">Error:</span> {{ error|escape }}
                            </span>
                        {% endfor %}
                    {% endif %}

                    {# We include the ACE editor here, but hidden, in order to use ACE's formatting.  #}
                    <div class="govuk-textarea" id="gov-uk-sql-wrapper" style="display: none;">
                        <div id="ace-sql-editor" data-disabled="true">{% if form.sql.value %}{{ form.sql.value }}{% endif %}</div>
                    </div>
                    <textarea class="govuk-textarea" aria-label="Sql" name="sql" id="original-sql" rows="15" readonly>{% if form.sql.value %}{{ form.sql.value }}{% endif %}</textarea>
                </div>

                <div class="govuk-form-group">
                    <button class="govuk-button" data-module="govuk-button" name="action" value="save">
                        Save
                    </button>
                    <button class="govuk-button govuk-button--secondary govuk-!-margin-left-4" data-module="govuk-button" type="button" id="format_button">
                        Format SQL
                    </button>
                    <button class="govuk-button govuk-button--secondary govuk-!-margin-left-4" data-module="govuk-button" type="button" id="unformat_button">
                        Reset format
                    </button>
                    <button class="govuk-button govuk-button--secondary govuk-!-margin-left-4" data-module="govuk-button" name="action" value="edit">
                        Edit SQL
                    </button>

                </div>
                </form>
            </fieldset>
        </div>

        <div id="schema" style="display: none;">
            <iframe src="about:blank" height="828px" frameBorder="0" id="schema_frame"></iframe>
        </div>
    </div>
</div>

{% load render_bundle from webpack_loader %}
{% render_bundle 'query' %}

{% endblock content %}